version: "3.8"

services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: utsav
      MYSQL_DATABASE: product_db
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  springboot-restful-webservices:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - springboot-mysql-net
    restart: on-failure

networks:
  springboot-mysql-net:
